import { useState, useEffect } from "react";
import { settingsApi } from "../../services/api";
import {
  FiShield, FiSave, FiRefreshCw, FiCopy, FiCheck,
  FiPlus, FiTrash2, FiAlertTriangle, FiEye,
  FiCode, FiChevronRight, FiDownload, FiUpload,
  FiClock, FiGlobe, FiX, FiInfo, FiZap,
} from "react-icons/fi";
import { HiOutlineCommandLine, HiOutlineShieldCheck } from "react-icons/hi2";

// ─── Default robots.txt content ───────────────────────────────────────────────
const DEFAULT_ROBOTS = `# Kraviona.com — robots.txt
# Generated by Kraviona CRM
# Last updated: Jun 2, 2026

User-agent: *
Allow: /
Disallow: /dashboard/
Disallow: /api/
Disallow: /admin/
Disallow: /_next/
Disallow: /private/

# Google
User-agent: Googlebot
Allow: /
Disallow: /dashboard/
Disallow: /api/

# Bing
User-agent: Bingbot
Allow: /
Disallow: /dashboard/

# Block AI Scrapers
User-agent: GPTBot
Disallow: /

User-agent: ChatGPT-User
Disallow: /

User-agent: CCBot
Disallow: /

# Sitemap
Sitemap: https://kraviona.com/sitemap.xml
Sitemap: https://kraviona.com/sitemap-blog.xml

# Crawl-delay
Crawl-delay: 1`;

const HISTORY = [
  { version: "v4", date: "Jun 2, 2026 · 7:54 AM",  author: "Admin", note: "Added AI scraper blocks" },
  { version: "v3", date: "May 20, 2026 · 3:12 PM", author: "Admin", note: "Added blog sitemap" },
  { version: "v2", date: "Apr 11, 2026 · 10:00 AM",author: "Admin", note: "Blocked /private/ path" },
  { version: "v1", date: "Jan 1, 2026 · 9:00 AM",  author: "Admin", note: "Initial robots.txt" },
];

const QUICK_RULES = [
  { label: "Block GPTBot",        snippet: "\nUser-agent: GPTBot\nDisallow: /\n" },
  { label: "Block ChatGPT-User",  snippet: "\nUser-agent: ChatGPT-User\nDisallow: /\n" },
  { label: "Block CCBot",         snippet: "\nUser-agent: CCBot\nDisallow: /\n" },
  { label: "Block all bots",      snippet: "\nUser-agent: *\nDisallow: /\n" },
  { label: "Allow all",           snippet: "\nUser-agent: *\nAllow: /\n" },
  { label: "Add Sitemap",         snippet: "\nSitemap: https://kraviona.com/sitemap.xml\n" },
  { label: "Crawl-delay: 2",      snippet: "\nCrawl-delay: 2\n" },
  { label: "Disallow /api/",      snippet: "\nDisallow: /api/\n" },
];

// ─── Parse robots.txt into structured rules for visual view ──────────────────
function parseRobots(txt) {
  const blocks = [];
  let current = null;
  txt.split("\n").forEach((line) => {
    const trimmed = line.trim();
    if (trimmed.startsWith("#") || trimmed === "") return;
    if (trimmed.toLowerCase().startsWith("user-agent:")) {
      if (current) blocks.push(current);
      current = { agent: trimmed.split(":")[1].trim(), rules: [] };
    } else if (current && (trimmed.toLowerCase().startsWith("allow:") || trimmed.toLowerCase().startsWith("disallow:"))) {
      const [key, ...rest] = trimmed.split(":");
      current.rules.push({ type: key.trim().toLowerCase(), path: rest.join(":").trim() });
    } else if (trimmed.toLowerCase().startsWith("sitemap:")) {
      blocks.push({ sitemap: trimmed.split(":").slice(1).join(":").trim() });
    }
  });
  if (current) blocks.push(current);
  return blocks;
}

// ─── Component ────────────────────────────────────────────────────────────────
export default function RobotsPage() {
  const [code, setCode] = useState(DEFAULT_ROBOTS);
  const [saved, setSaved] = useState(true);
  const [saving, setSaving] = useState(false);
  const [copied, setCopied] = useState(false);
  const [tab, setTab] = useState("editor"); // editor | visual | history
  const [toast, setToast] = useState(null);
  const [historyOpen, setHistoryOpen] = useState(false);

  useEffect(() => {
    settingsApi.public().then((s) => {
      if (s?.robotsTxt) setCode(s.robotsTxt);
    }).catch(() => null);
  }, []);

  const showToast = (msg, type = "success") => {
    setToast({ msg, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await settingsApi.single("robotsTxt", { value: code });
      setSaved(true);
      showToast("robots.txt saved & deployed to production");
    } catch (e) {
      showToast("Save failed: " + e.message, "error");
    } finally { setSaving(false); }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleReset = () => {
    setCode(DEFAULT_ROBOTS);
    setSaved(false);
    showToast("Reset to default template", "info");
  };

  const insertSnippet = (snippet) => {
    setCode((prev) => prev + snippet);
    setSaved(false);
  };

  const parsed = parseRobots(code);
  const lineCount = code.split("\n").length;
  const hasIssues = code.includes("Disallow: /\n") && !code.includes("User-agent: *\nAllow:");

  return (
    <div className="min-h-screen bg-[#F7F8FA]" style={{ fontFamily: "'DM Sans', sans-serif" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap');
        .mono { font-family: 'JetBrains Mono', monospace; }
        .editor-area {
          resize: none;
          outline: none;
          tab-size: 2;
        }
        .editor-area::selection { background: #E8663D30; }
        @keyframes slideDown {
          from { opacity:0; transform: translateY(-8px); }
          to   { opacity:1; transform: translateY(0); }
        }
        .toast { animation: slideDown 0.25s ease; }
      `}</style>

      {/* Toast */}
      {toast && (
        <div className={`toast fixed top-5 right-5 z-[100] flex items-center gap-3 px-5 py-3 rounded-2xl shadow-2xl text-sm font-semibold ${
          toast.type === "success" ? "bg-emerald-600 text-white" :
          toast.type === "info"    ? "bg-gray-800 text-white" :
          "bg-red-500 text-white"
        }`}>
          {toast.type === "success" ? <FiCheck size={15} /> : <FiInfo size={15} />}
          {toast.msg}
        </div>
      )}

      {/* ── Top Bar ── */}
      <div className="bg-white border-b border-gray-100 px-6 py-4 sticky top-0 z-30 shadow-sm">
        <div className="max-w-[1100px] mx-auto flex items-center justify-between">
          <div>
            <div className="flex items-center gap-1.5 text-xs text-gray-400 mb-0.5">
              <span>Settings</span>
              <FiChevronRight size={11} />
              <span>SEO & Meta</span>
              <FiChevronRight size={11} />
              <span className="text-gray-700 font-semibold">Robots.txt Editor</span>
            </div>
            <h1 className="text-xl font-extrabold text-gray-800 flex items-center gap-2 tracking-tight">
              <FiShield size={20} className="text-[#E8663D]" />
              Robots.txt Editor
            </h1>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3.5 py-2 text-xs font-bold border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors text-gray-600"
            >
              {copied ? <FiCheck size={13} className="text-emerald-500" /> : <FiCopy size={13} />}
              {copied ? "Copied!" : "Copy"}
            </button>
            <button
              onClick={handleReset}
              className="flex items-center gap-2 px-3.5 py-2 text-xs font-bold border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors text-gray-600"
            >
              <FiRefreshCw size={13} />
              Reset
            </button>
            <button
              onClick={handleSave}
              disabled={saved && !saving}
              className={`flex items-center gap-2 px-4 py-2 text-sm font-bold rounded-xl transition-all active:scale-95 ${
                saved ? "bg-gray-100 text-gray-400 cursor-default" : "text-white shadow-lg hover:-translate-y-0.5"
              }`}
              style={!saved ? { background: "linear-gradient(135deg,#E8663D,#d45a30)" } : {}}
            >
              {saving
                ? <><FiRefreshCw size={13} className="animate-spin" /> Saving…</>
                : saved
                ? <><FiCheck size={13} className="text-emerald-500" /> Saved</>
                : <><FiSave size={13} /> Save & Deploy</>}
            </button>
          </div>
        </div>
      </div>

      <div className="px-6 py-6 max-w-[1100px] mx-auto">

        {/* ── Info Banner ── */}
        <div className="flex items-start gap-3 bg-blue-50 border border-blue-100 rounded-xl px-5 py-3 mb-5">
          <FiInfo size={15} className="text-blue-500 mt-0.5 shrink-0" />
          <p className="text-sm text-blue-700">
            This file is served at <code className="bg-white/70 px-1.5 py-0.5 rounded text-xs font-mono">https://kraviona.com/robots.txt</code>. 
            Changes are deployed immediately after saving. Google re-reads this file during each crawl.
          </p>
        </div>

        {/* ── Issue Warning ── */}
        {hasIssues && (
          <div className="flex items-start gap-3 bg-amber-50 border border-amber-200 rounded-xl px-5 py-3 mb-5">
            <FiAlertTriangle size={15} className="text-amber-500 mt-0.5 shrink-0" />
            <p className="text-sm text-amber-700">
              <strong>Warning:</strong> A <code className="bg-white/70 px-1 rounded text-xs">Disallow: /</code> rule is present. This may block search engines from crawling your site.
            </p>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">

          {/* ── Left: Editor + Tabs ── */}
          <div className="lg:col-span-2 space-y-4">

            {/* Tab Bar */}
            <div className="flex items-center gap-1 bg-white border border-gray-100 rounded-xl p-1 shadow-sm w-fit">
              {[
                { id: "editor", label: "Editor",      icon: FiCode },
                { id: "visual", label: "Visual View",  icon: FiEye },
                { id: "history",label: "History",      icon: FiClock },
              ].map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setTab(id)}
                  className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-bold transition-all ${
                    tab === id ? "bg-[#E8663D] text-white shadow-sm" : "text-gray-500 hover:bg-gray-50"
                  }`}
                >
                  <Icon size={12} />
                  {label}
                </button>
              ))}
            </div>

            {/* Editor Tab */}
            {tab === "editor" && (
              <div className="bg-[#0F1117] rounded-2xl overflow-hidden shadow-xl border border-gray-800">
                {/* Editor Top Bar */}
                <div className="flex items-center justify-between px-5 py-3 border-b border-gray-800">
                  <div className="flex items-center gap-2">
                    <span className="w-3 h-3 rounded-full bg-red-500" />
                    <span className="w-3 h-3 rounded-full bg-yellow-500" />
                    <span className="w-3 h-3 rounded-full bg-green-500" />
                    <span className="ml-3 text-gray-500 text-xs mono">robots.txt</span>
                  </div>
                  <div className="flex items-center gap-3 text-gray-600 text-xs mono">
                    <span>{lineCount} lines</span>
                    <span>{code.length} chars</span>
                  </div>
                </div>

                {/* Line Numbers + Textarea */}
                <div className="flex overflow-hidden">
                  {/* Line numbers */}
                  <div className="select-none bg-[#0F1117] px-3 py-4 text-right mono text-xs text-gray-700 leading-6 min-w-[3rem]"
                    style={{ userSelect: "none" }}>
                    {Array.from({ length: lineCount }, (_, i) => (
                      <div key={i}>{i + 1}</div>
                    ))}
                  </div>
                  {/* Editor */}
                  <textarea
                    value={code}
                    onChange={(e) => { setCode(e.target.value); setSaved(false); }}
                    className="editor-area mono flex-1 bg-[#0F1117] text-gray-100 text-sm leading-6 px-4 py-4 min-h-[520px] border-l border-gray-800"
                    spellCheck={false}
                    style={{ caretColor: "#E8663D" }}
                  />
                </div>

                {/* Syntax legend */}
                <div className="flex items-center gap-4 px-5 py-2.5 border-t border-gray-800">
                  {[
                    { dot: "bg-gray-500",   label: "Comment (#)" },
                    { dot: "bg-blue-400",   label: "User-agent" },
                    { dot: "bg-emerald-400",label: "Allow" },
                    { dot: "bg-red-400",    label: "Disallow" },
                    { dot: "bg-yellow-400", label: "Sitemap" },
                  ].map(({ dot, label }) => (
                    <div key={label} className="flex items-center gap-1.5">
                      <span className={`w-2 h-2 rounded-full ${dot}`} />
                      <span className="text-gray-600 text-[10px] mono">{label}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Visual Tab */}
            {tab === "visual" && (
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-5 py-4 border-b border-gray-50">
                  <h3 className="font-bold text-gray-800 text-sm flex items-center gap-2">
                    <FiEye size={15} className="text-[#E8663D]" /> Parsed Rules
                  </h3>
                  <p className="text-xs text-gray-400 mt-0.5">{parsed.length} directive blocks detected</p>
                </div>
                <div className="p-5 space-y-4">
                  {parsed.map((block, i) => {
                    if (block.sitemap) {
                      return (
                        <div key={i} className="flex items-center gap-3 p-4 bg-yellow-50 border border-yellow-100 rounded-xl">
                          <FiGlobe size={16} className="text-yellow-600 shrink-0" />
                          <div>
                            <div className="text-xs font-bold text-yellow-700 uppercase tracking-wide">Sitemap</div>
                            <div className="text-sm text-yellow-800 font-mono">{block.sitemap}</div>
                          </div>
                        </div>
                      );
                    }
                    return (
                      <div key={i} className="rounded-xl border border-gray-100 overflow-hidden">
                        <div className="flex items-center gap-2 px-4 py-3 bg-gray-50 border-b border-gray-100">
                          <FiShield size={13} className="text-blue-500" />
                          <span className="text-xs font-bold text-blue-600 mono">User-agent: {block.agent}</span>
                        </div>
                        <div className="divide-y divide-gray-50">
                          {block.rules?.map((rule, ri) => (
                            <div key={ri} className={`flex items-center gap-3 px-4 py-2.5 ${rule.type === "allow" ? "bg-emerald-50/40" : "bg-red-50/40"}`}>
                              <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full mono ${
                                rule.type === "allow"
                                  ? "bg-emerald-100 text-emerald-700"
                                  : "bg-red-100 text-red-600"
                              }`}>
                                {rule.type}
                              </span>
                              <span className="text-sm text-gray-700 mono">{rule.path || "/"}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* History Tab */}
            {tab === "history" && (
              <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-5 py-4 border-b border-gray-50">
                  <h3 className="font-bold text-gray-800 text-sm flex items-center gap-2">
                    <FiClock size={15} className="text-[#E8663D]" /> Version History
                  </h3>
                  <p className="text-xs text-gray-400 mt-0.5">Last 4 saved versions</p>
                </div>
                <div className="divide-y divide-gray-50">
                  {HISTORY.map((h, i) => (
                    <div key={i} className="flex items-center justify-between px-5 py-4 hover:bg-gray-50 transition-colors group">
                      <div className="flex items-center gap-3">
                        <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${i === 0 ? "bg-[#E8663D]/10" : "bg-gray-100"}`}>
                          <FiCode size={13} className={i === 0 ? "text-[#E8663D]" : "text-gray-400"} />
                        </div>
                        <div>
                          <div className="flex items-center gap-2">
                            <span className="text-sm font-bold text-gray-700">{h.version}</span>
                            {i === 0 && <span className="px-1.5 py-0.5 bg-[#E8663D]/10 text-[#E8663D] text-[10px] font-bold rounded-md">Current</span>}
                          </div>
                          <div className="text-xs text-gray-400">{h.date} · {h.author}</div>
                          <div className="text-xs text-gray-500 mt-0.5">{h.note}</div>
                        </div>
                      </div>
                      {i !== 0 && (
                        <button className="opacity-0 group-hover:opacity-100 text-xs font-semibold text-[#E8663D] hover:underline transition-opacity">
                          Restore
                        </button>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* ── Right: Quick Rules + Info ── */}
          <div className="space-y-4">

            {/* Quick Insert */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="px-5 py-4 border-b border-gray-50">
                <h3 className="font-bold text-gray-800 text-sm flex items-center gap-2">
                  <FiZap size={14} className="text-[#E8663D]" /> Quick Insert
                </h3>
                <p className="text-xs text-gray-400 mt-0.5">Click to append to your file</p>
              </div>
              <div className="p-4 grid grid-cols-1 gap-2">
                {QUICK_RULES.map(({ label, snippet }) => (
                  <button
                    key={label}
                    onClick={() => insertSnippet(snippet)}
                    className="flex items-center justify-between px-3.5 py-2.5 text-xs font-semibold text-gray-700 bg-gray-50 hover:bg-[#FFF4F0] hover:text-[#E8663D] border border-transparent hover:border-[#E8663D]/20 rounded-xl transition-all text-left group"
                  >
                    <span>{label}</span>
                    <FiPlus size={12} className="text-gray-400 group-hover:text-[#E8663D] transition-colors" />
                  </button>
                ))}
              </div>
            </div>

            {/* File Info */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 space-y-3">
              <h3 className="font-bold text-gray-800 text-sm flex items-center gap-2">
                <FiInfo size={14} className="text-[#E8663D]" /> File Info
              </h3>
              {[
                { label: "URL",        value: "kraviona.com/robots.txt" },
                { label: "Lines",      value: `${lineCount}` },
                { label: "Characters", value: `${code.length}` },
                { label: "Blocks",     value: `${parsed.length} directive groups` },
                { label: "Last saved", value: "Jun 2, 2026 · 7:54 AM" },
                { label: "Status",     value: "Live ✓" },
              ].map(({ label, value }) => (
                <div key={label} className="flex items-center justify-between">
                  <span className="text-xs text-gray-400">{label}</span>
                  <span className="text-xs font-semibold text-gray-700 mono">{value}</span>
                </div>
              ))}
            </div>

            {/* Best Practices */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
              <h3 className="font-bold text-gray-800 text-sm flex items-center gap-2 mb-3">
                <HiOutlineShieldCheck size={15} className="text-emerald-500" /> Best Practices
              </h3>
              <ul className="space-y-2">
                {[
                  "Always include a Sitemap directive",
                  "Block /api/ and /dashboard/ paths",
                  "Consider blocking AI scrapers (GPTBot etc.)",
                  "Don't disallow CSS/JS — Google needs them",
                  "Use specific paths not wildcard Disallow: /",
                  "Test with Google Search Console",
                ].map((tip) => (
                  <li key={tip} className="flex items-start gap-2 text-xs text-gray-500">
                    <FiCheck size={11} className="text-emerald-500 mt-0.5 shrink-0" />
                    {tip}
                  </li>
                ))}
              </ul>
            </div>

            {/* Actions */}
            <div className="flex gap-2">
              <button
                onClick={() => {
                  const blob = new Blob([code], { type: "text/plain" });
                  const a = document.createElement("a");
                  a.href = URL.createObjectURL(blob);
                  a.download = "robots.txt";
                  a.click();
                }}
                className="flex-1 flex items-center justify-center gap-2 py-2.5 text-xs font-bold border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors text-gray-600"
              >
                <FiDownload size={13} /> Export
              </button>
              <button className="flex-1 flex items-center justify-center gap-2 py-2.5 text-xs font-bold border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors text-gray-600">
                <FiUpload size={13} /> Import
              </button>
            </div>

          </div>
        </div>
      </div>
    </div>
  );
}