// Seed data for all 11 service detail pages.
// Each wrapper passes its slug → looks up data here.

export const SERVICE_PAGE_DATA = {
  "mern-stack-development": {
    icon: "⚡",
    heroTitle: "MERN Stack Development",
    heroDescription: "MongoDB, Express, React & Node.js full-stack apps engineered for scale.",
    heroImage: "/services/mern.png",
    isActive: true,
    whyChoose: [
      "Single JavaScript language across the entire stack",
      "Faster time-to-market with Agile sprint delivery",
      "Horizontally scalable MongoDB architecture",
      "Rich open-source ecosystem and community support",
      "Cost-effective for startups, mid-market, and enterprises",
    ],
    features: [
      { title: "MongoDB Database Design",   description: "Flexible NoSQL schemas for modern apps with indexes, sharding, and replication." },
      { title: "Express.js REST API",       description: "Secure, versioned RESTful APIs with auth, validation, and rate-limiting middleware." },
      { title: "React.js Frontend",         description: "Dynamic React.js UIs with Server-Side Rendering via Next.js." },
      { title: "Node.js Backend",           description: "Event-driven, non-blocking server architecture for high concurrency." },
      { title: "JWT Authentication",        description: "Secure, stateless authentication and granular role-based authorization." },
      { title: "Cloud Deployment",          description: "Production-ready deployment on AWS / Vercel / Railway with CI/CD pipelines." },
    ],
    technologies: ["MongoDB", "Express.js", "React.js", "Node.js"],
    faqs: [
      { question: "How long does a MERN Stack project take?", answer: "Typically 4-12 weeks depending on scope. We deliver in 2-week sprints with weekly demos." },
      { question: "Do you provide ongoing support?",          answer: "Yes — monthly retainers cover bug fixes, security patches, and minor feature additions." },
      { question: "Can you migrate our existing app to MERN?", answer: "Absolutely. We do zero-downtime migrations with dual-write strategies and feature flags." },
    ],
    relatedServices: ["full-stack-development", "react-development", "nodejs-development", "database-architecture"],
    seo: { metaTitle: "MERN Stack Development Services | Kraviona", metaDescription: "Expert MERN stack development — MongoDB, Express, React, Node.js. Scalable full-stack apps for startups & enterprises.", canonicalUrl: "https://kraviona.com/services/mern-stack-development", ogImage: "" },
  },

  "full-stack-development": {
    icon: "💻", heroTitle: "Full-Stack Development",
    heroDescription: "End-to-end web solutions from database to pixel-perfect UI.",
    heroImage: "/services/fullstack.png", isActive: true,
    whyChoose: ["One team owns end-to-end delivery", "Tight feedback loops between frontend & backend", "Senior generalist engineers, not handoff chains", "Faster iteration cycles", "Lower coordination overhead"],
    features: [
      { title: "Architecture Planning",    description: "We start with whiteboard sessions and ADRs before writing a line of code." },
      { title: "Frontend & Backend",       description: "React/Next.js paired with Node.js or Python backends — your choice." },
      { title: "API Design",               description: "REST or GraphQL, fully versioned and documented." },
      { title: "Database Setup",           description: "MongoDB, PostgreSQL, or both — designed for your access patterns." },
      { title: "DevOps & CI/CD",           description: "GitHub Actions, automated tests, staging environments, infra-as-code." },
      { title: "Testing & QA",             description: "Unit + integration + E2E tests with >80% coverage on core paths." },
    ],
    technologies: ["React", "Node.js", "PostgreSQL", "Docker"],
    faqs: [
      { question: "What stack do you use?",                  answer: "Default to MERN / Next.js + Node, but happy to use Python/Django/Postgres when it's the right tool." },
      { question: "Do you do mobile too?",                   answer: "Yes — React Native and Flutter for cross-platform builds." },
      { question: "How small a team will you accept?",       answer: "Minimum engagement is 1 senior engineer for 1 month." },
    ],
    relatedServices: ["mern-stack-development", "react-development", "backend-development", "saas-development"],
    seo: { metaTitle: "Full-Stack Web Development | Kraviona", metaDescription: "End-to-end full-stack development — frontend, backend, DB, DevOps. One senior team, no handoffs.", canonicalUrl: "https://kraviona.com/services/full-stack-development", ogImage: "" },
  },

  "react-development": {
    icon: "⚛", heroTitle: "React.js Development",
    heroDescription: "High-performance SPAs and Next.js apps with SSR.",
    heroImage: "/services/react.png", isActive: true,
    whyChoose: ["Specialised in React + Next.js since 2018", "Web Vitals 90+ as the baseline, not the goal", "Strict TypeScript everywhere", "Reusable design-system component libraries", "Production-grade SSR and ISR architectures"],
    features: [
      { title: "Component Library",     description: "Custom design-system in Storybook with full a11y coverage." },
      { title: "State Management",      description: "Zustand, Redux Toolkit, or React Query — whichever fits your needs." },
      { title: "SSR / SSG / ISR",       description: "Server-rendered pages with smart caching for SEO + speed." },
      { title: "Performance",           description: "Bundle splitting, lazy loading, partial hydration, image optimisation." },
      { title: "Testing",               description: "Vitest + React Testing Library + Playwright E2E." },
      { title: "Accessibility",         description: "WCAG 2.1 AA compliant by default, audited via axe." },
    ],
    technologies: ["React", "Next.js", "TypeScript", "Redux"],
    faqs: [
      { question: "Do you migrate legacy React apps?", answer: "Yes — class-component → hooks migrations are bread-and-butter for us." },
      { question: "Next.js or vanilla React?",         answer: "Default to Next.js for SEO-sensitive projects, vanilla React for internal dashboards." },
      { question: "Do you build component libraries?", answer: "We ship Storybook-documented design systems on most engagements." },
    ],
    relatedServices: ["mern-stack-development", "full-stack-development", "web-performance-optimization"],
    seo: { metaTitle: "React.js Development Services | Kraviona", metaDescription: "Senior React.js development — SSR, Next.js, TypeScript, design systems, Web Vitals 90+.", canonicalUrl: "https://kraviona.com/services/react-development", ogImage: "" },
  },

  "nodejs-development": {
    icon: "🟢", heroTitle: "Node.js Development",
    heroDescription: "Scalable APIs and real-time backend systems.",
    heroImage: "/services/node.png", isActive: true,
    whyChoose: ["Event-driven, non-blocking I/O", "Same language as your frontend = shared tooling", "Massive npm ecosystem", "Native WebSocket and streaming support", "Battle-tested at billion-request scale"],
    features: [
      { title: "REST APIs",        description: "Express + OpenAPI-documented REST APIs with full test coverage." },
      { title: "GraphQL",          description: "Apollo Server with type-safe schemas and dataloader patterns." },
      { title: "WebSockets",       description: "Real-time chat, live dashboards, presence, multiplayer." },
      { title: "Microservices",    description: "NATS / Kafka-backed service meshes when you need to scale teams." },
      { title: "Auth Systems",     description: "JWT, OAuth, SSO, MFA — all the patterns, none of the headaches." },
      { title: "Cloud Deploy",     description: "AWS Lambda, Fargate, EC2, or self-hosted — your call." },
    ],
    technologies: ["Node.js", "Express", "Socket.io", "Redis"],
    faqs: [
      { question: "Express, NestJS, or Fastify?",       answer: "We default to Express for simple APIs, NestJS for large enterprise codebases." },
      { question: "Can you scale to 10k+ RPS?",          answer: "Yes — we've shipped APIs handling 50k+ RPS sustained with horizontal autoscaling." },
      { question: "Do you handle queues & workers?",     answer: "BullMQ, RabbitMQ, SQS — pick your poison." },
    ],
    relatedServices: ["backend-development", "api-development", "saas-development"],
    seo: { metaTitle: "Node.js Development Services | Kraviona", metaDescription: "Scalable Node.js backends, real-time APIs, WebSockets, microservices.", canonicalUrl: "https://kraviona.com/services/nodejs-development", ogImage: "" },
  },

  "backend-development": {
    icon: "⚙️", heroTitle: "Backend Development",
    heroDescription: "Robust, secure server-side logic and system design.",
    heroImage: "/services/backend.png", isActive: true,
    whyChoose: ["Systems thinking, not just CRUD", "Security by default — OWASP-aware everywhere", "p95 latency obsession", "Observability baked in (logs/metrics/traces)", "Domain-driven design when complexity demands it"],
    features: [
      { title: "System Architecture",  description: "C4 diagrams, ADRs, and capacity planning before any code is written." },
      { title: "API Design",           description: "REST, GraphQL, gRPC — chosen for the use case, documented obsessively." },
      { title: "Auth & RBAC",          description: "JWT, session-based, OAuth2, MFA, fine-grained role permissions." },
      { title: "Caching",              description: "Redis + CDN + in-memory layers, with proper invalidation strategies." },
      { title: "Queues & Workers",     description: "BullMQ, Kafka, SQS — async-everything-that-can-be." },
      { title: "Monitoring",           description: "Datadog, Grafana, Sentry — you'll know it's broken before users do." },
    ],
    technologies: ["Node.js", "PostgreSQL", "Redis", "RabbitMQ"],
    faqs: [
      { question: "Do you build event-driven architectures?", answer: "Yes — CQRS / event-sourcing patterns when the domain calls for it." },
      { question: "Can you handle compliance work?",          answer: "HIPAA, SOC 2, GDPR — we've shipped systems certified against all three." },
      { question: "Do you do code audits?",                   answer: "Yes — 2-3 day deep audits with written remediation plans." },
    ],
    relatedServices: ["api-development", "database-architecture", "nodejs-development"],
    seo: { metaTitle: "Backend Engineering Services | Kraviona", metaDescription: "Production-grade backend engineering — architecture, APIs, auth, caching, queues, observability.", canonicalUrl: "https://kraviona.com/services/backend-development", ogImage: "" },
  },

  "api-development": {
    icon: "🔌", heroTitle: "API Development",
    heroDescription: "Custom RESTful and GraphQL APIs built for performance.",
    heroImage: "/services/api.png", isActive: true,
    whyChoose: ["OpenAPI / GraphQL schemas from day one", "Versioning strategy that doesn't paint you into a corner", "Auto-generated SDKs for clients", "Rate limiting + quota enforcement", "End-to-end auth tests on every PR"],
    features: [
      { title: "RESTful APIs",      description: "Resource-oriented, HATEOAS where it makes sense, versioned via URL or header." },
      { title: "GraphQL APIs",      description: "Type-safe schemas, dataloaders, persisted queries, federation when needed." },
      { title: "API Documentation", description: "Swagger UI / Redoc / GraphQL Playground published with each release." },
      { title: "Versioning",        description: "Sunset policies, backward-compat windows, deprecation notices." },
      { title: "Rate Limiting",     description: "Per-user, per-endpoint, sliding-window, with 429 + Retry-After." },
      { title: "Testing",           description: "Contract tests, integration tests, fuzz tests on inputs." },
    ],
    technologies: ["Express", "GraphQL", "Swagger", "Jest"],
    faqs: [
      { question: "REST or GraphQL for my project?", answer: "REST for public APIs / mobile clients. GraphQL for complex internal data needs." },
      { question: "Do you publish SDKs?",            answer: "Yes — auto-generated TypeScript / Python / Go SDKs on every release." },
      { question: "What about webhooks?",            answer: "We design webhook subscriptions, retries, and signature verification." },
    ],
    relatedServices: ["backend-development", "nodejs-development", "saas-development"],
    seo: { metaTitle: "API Development Services | Kraviona", metaDescription: "REST and GraphQL API development with OpenAPI docs, SDK generation, versioning, and rate limiting.", canonicalUrl: "https://kraviona.com/services/api-development", ogImage: "" },
  },

  "database-architecture": {
    icon: "🗄️", heroTitle: "Database Architecture",
    heroDescription: "Optimised MongoDB, PostgreSQL & Redis structures.",
    heroImage: "/services/database.png", isActive: true,
    whyChoose: ["Schemas designed around access patterns, not entities", "Query plans reviewed for every hot path", "Backups + DR drills, not just backups", "Multi-region replicas when latency matters", "Zero-downtime migrations as default"],
    features: [
      { title: "Schema Design",         description: "Logical → physical → access-pattern-driven schemas." },
      { title: "Indexing",              description: "Compound, partial, sparse indexes — the right one for each query." },
      { title: "Query Optimisation",    description: "EXPLAIN reviews, p95 tracking, slow-query alerting." },
      { title: "Replication",           description: "Read replicas, multi-AZ, automated failover with PITR." },
      { title: "Backup Strategy",       description: "Daily snapshots, hourly WAL shipping, monthly DR drills." },
      { title: "Migration",             description: "Zero-downtime migrations using dual-writes & feature flags." },
    ],
    technologies: ["MongoDB", "PostgreSQL", "Redis", "Mongoose"],
    faqs: [
      { question: "Mongo or Postgres?",                     answer: "We pick based on workload: Postgres for relational + ACID, Mongo for flexible document schemas." },
      { question: "Do you do database migrations?",         answer: "Yes — millions-of-rows migrations with zero downtime." },
      { question: "What about Redis & caching layers?",     answer: "We design write-through, write-behind, and cache-aside patterns based on your read/write ratio." },
    ],
    relatedServices: ["backend-development", "mern-stack-development", "api-development"],
    seo: { metaTitle: "Database Architecture Services | Kraviona", metaDescription: "Senior database architecture — MongoDB, PostgreSQL, Redis. Schema design, indexing, replication, migrations.", canonicalUrl: "https://kraviona.com/services/database-architecture", ogImage: "" },
  },

  "saas-development": {
    icon: "☁️", heroTitle: "SaaS Development",
    heroDescription: "Scalable multi-tenant SaaS platforms with billing & auth.",
    heroImage: "/services/saas.png", isActive: true,
    whyChoose: ["Multi-tenancy patterns done right (schema vs row-level)", "Stripe / Paddle integrated for global subscriptions", "Self-serve onboarding flows that convert", "Admin panels built into every product", "Usage-based billing when flat-rate doesn't fit"],
    features: [
      { title: "Multi-Tenancy",         description: "Schema-per-tenant or row-level tenancy — whichever fits your scale." },
      { title: "Subscription Billing",  description: "Stripe / Paddle integration, prorations, trials, dunning automation." },
      { title: "OAuth / SSO",           description: "Google, GitHub, SAML, SCIM provisioning for enterprise tiers." },
      { title: "Analytics",             description: "Per-tenant usage dashboards, conversion funnels, retention cohorts." },
      { title: "Admin Panel",           description: "Built-in CRUD admin so your ops team isn't blocked on engineering." },
      { title: "Scalability",           description: "Horizontal scaling across tenants from day one." },
    ],
    technologies: ["Node.js", "Stripe", "Auth0", "AWS"],
    faqs: [
      { question: "How do you handle multi-tenancy?",       answer: "Most projects use row-level tenancy with PostgreSQL RLS. Heavy enterprise plays get schema-per-tenant." },
      { question: "Do you build the marketing site too?",   answer: "Yes — Next.js marketing + Webflow CMS are common pairings." },
      { question: "Do you handle compliance for SaaS?",     answer: "GDPR, SOC 2 Type II, HIPAA — we've shipped against all three." },
    ],
    relatedServices: ["mern-stack-development", "backend-development", "api-development", "full-stack-development"],
    seo: { metaTitle: "SaaS Development Services | Kraviona", metaDescription: "Build production SaaS platforms — multi-tenant architecture, Stripe billing, SSO, admin panels.", canonicalUrl: "https://kraviona.com/services/saas-development", ogImage: "" },
  },

  "technical-seo": {
    icon: "📈", heroTitle: "Technical SEO",
    heroDescription: "Core Web Vitals, crawlability, and structured data.",
    heroImage: "/services/seo.png", isActive: true,
    whyChoose: ["Engineering-led SEO, not blog spam", "Core Web Vitals as KPI, not afterthought", "Site speed + schema + indexability together", "JS-SEO expertise (Next.js, Nuxt, hydration issues)", "Monthly reporting tied to organic traffic + revenue"],
    features: [
      { title: "Site Audit",            description: "Lighthouse, Screaming Frog, Search Console deep dive with prioritised fix list." },
      { title: "Core Web Vitals",       description: "LCP, CLS, INP — measured, optimised, monitored." },
      { title: "Schema Markup",         description: "JSON-LD for Articles, Products, FAQs, Breadcrumbs, Organisation." },
      { title: "Sitemap & robots.txt",  description: "Dynamic XML sitemaps, hreflang, robots.txt directives." },
      { title: "Indexation Strategy",   description: "Canonicals, redirects, no-index rules — laser-focused on quality." },
      { title: "Crawl Fix",             description: "Render-blocking, JS-SEO debugging, hydration hydration issues." },
    ],
    technologies: ["Screaming Frog", "PageSpeed", "Search Console", "Ahrefs"],
    faqs: [
      { question: "How soon will I see results?",      answer: "Technical fixes usually show in indexing in 2-4 weeks. Ranking lifts typically 60-90 days." },
      { question: "Do you write content too?",         answer: "Technical SEO only — we partner with content agencies for editorial work." },
      { question: "Do you handle JS-SEO?",             answer: "Next.js, Nuxt, Remix hydration debugging is a specialty." },
    ],
    relatedServices: ["web-performance-optimization", "mern-stack-development", "react-development"],
    seo: { metaTitle: "Technical SEO Services | Kraviona", metaDescription: "Engineering-led Technical SEO — Core Web Vitals, schema markup, sitemaps, JS-SEO debugging.", canonicalUrl: "https://kraviona.com/services/technical-seo", ogImage: "" },
  },

  "web-performance-optimization": {
    icon: "🚀", heroTitle: "Web Performance Optimization",
    heroDescription: "Lighthouse 90+ scores and real-user speed improvements.",
    heroImage: "/services/perf.png", isActive: true,
    whyChoose: ["Real-user monitoring (RUM), not just lab tests", "p75 LCP < 2.5s as our delivery target", "Bundle-size audits with module-by-module breakdowns", "Image + font optimisation pipelines", "Server-side performance, not just client"],
    features: [
      { title: "Lighthouse Audit",       description: "Full-page audit with prioritised remediation plan." },
      { title: "Image Optimisation",     description: "AVIF/WebP, responsive srcsets, lazy loading, CDN delivery." },
      { title: "Code Splitting",         description: "Route-level + component-level splits to shrink critical path." },
      { title: "CDN Setup",              description: "Cloudflare, Fastly, BunnyCDN — edge caching tuned to your traffic." },
      { title: "Lazy Loading",           description: "Intersection-observer driven hydration & component loading." },
      { title: "Caching",                description: "Browser cache, service workers, CDN cache, server cache — all layers tuned." },
    ],
    technologies: ["Webpack", "Next.js", "Cloudinary", "Vercel"],
    faqs: [
      { question: "Will I hit Lighthouse 100?",         answer: "Realistic target is 90-100 on mobile, 95-100 on desktop. We get there 95% of the time." },
      { question: "Do you measure real-user perf?",     answer: "Yes — we set up SpeedCurve / Datadog RUM to track p75 across geographies." },
      { question: "Can you fix CLS issues?",            answer: "CLS is usually fixable in days, not weeks — most common cause is unreserved image dimensions." },
    ],
    relatedServices: ["technical-seo", "react-development", "mern-stack-development"],
    seo: { metaTitle: "Web Performance Optimization | Kraviona", metaDescription: "Lighthouse 90+ scores, p75 LCP < 2.5s, image optimisation, code splitting, CDN tuning.", canonicalUrl: "https://kraviona.com/services/web-performance-optimization", ogImage: "" },
  },

  "ai-automation": {
    icon: "🤖", heroTitle: "AI Automation",
    heroDescription: "LLM integration, AI workflows, and smart automation.",
    heroImage: "/services/ai.png", isActive: true,
    whyChoose: ["Production-ready LLM integrations, not demos", "RAG architectures with proper eval pipelines", "Vector DBs tuned for your data", "Cost-aware design (token budgets, caching)", "Guardrails + observability for AI outputs"],
    features: [
      { title: "LLM Integration",     description: "OpenAI, Anthropic, open-source — integrated with proper fallback chains." },
      { title: "Prompt Engineering",  description: "Templates, few-shot examples, output schemas, evals." },
      { title: "AI Pipelines",        description: "Chained workflows in LangChain / LlamaIndex with observability." },
      { title: "Data Processing",     description: "Document chunking, embedding pipelines, vector store population." },
      { title: "Chatbots",            description: "RAG-backed chatbots over your knowledge base with citations." },
      { title: "Embeddings",          description: "Domain-specific embeddings, hybrid search, reranking." },
    ],
    technologies: ["OpenAI", "LangChain", "Pinecone", "Python"],
    faqs: [
      { question: "Which LLM provider?",                 answer: "Anthropic Claude is our default for production. OpenAI for specific niches, open-source for cost-sensitive deployments." },
      { question: "How do you handle hallucinations?",   answer: "RAG + citations + output validation + structured-output schemas — layered defence." },
      { question: "Do you fine-tune models?",            answer: "Rarely — RAG + prompting usually outperforms fine-tuning at a fraction of the cost." },
    ],
    relatedServices: ["backend-development", "saas-development", "api-development"],
    seo: { metaTitle: "AI Automation & LLM Integration | Kraviona", metaDescription: "Production-ready AI automation — LLM integration, RAG, vector DBs, chatbots, prompt engineering.", canonicalUrl: "https://kraviona.com/services/ai-automation", ogImage: "" },
  },
};
